"""Remove paragraph model

Revision ID: a5e5f93235e0
Revises: 49c6ce48eba8
Create Date: 2024-09-11 16:37:02.677530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e5f93235e0'
down_revision = '49c6ce48eba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paragraph')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paragraph',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='paragraph_pkey')
    )
    # ### end Alembic commands ###
